n, m = map(int, input().split())
A = set(int(i) for i in input().split())
B = set([int(i) for i in input().split()])
inter = list(A.intersection(B))
inter.sort()
a = A.copy()
A.difference_update(B)
B.difference_update(a)
A = list(A)
B = list(B)
A.sort()
B.sort()
print(*inter)
print(*A)
print(*B)
